# Generated by Django 2.2.28 on 2026-06-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaznamKnihaProvozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('version', models.CharField(max_length=50, verbose_name='Verze')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('location', models.CharField(max_length=100, verbose_name='Místo ( adresar )')),
                ('command', models.CharField(max_length=200, verbose_name='Příkaz')),
                ('type_of_launch', models.CharField(max_length=50, verbose_name='Typ spuštění')),
                ('trigger_frequency', models.CharField(max_length=50, verbose_name='Frekvence spuštění')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('link_to_details', models.URLField(blank=True, null=True, verbose_name='Odkaz na detaily')),
                ('status', models.CharField(max_length=50, verbose_name='Stav')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Datum publikace')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zaznam kniha provozu',
                'verbose_name_plural': 'zaznamy kniha provozu',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='HistorieKnihaProvozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateTimeField(auto_now_add=True, verbose_name='Datum spuštění')),
                ('field_name', models.CharField(max_length=100, verbose_name='Pole')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Původní hodnota')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nová hodnota')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zaznam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id', to='kniha_provozu.ZaznamKnihaProvozu')),
            ],
            options={
                'verbose_name': 'Historie (kniha provozu)',
                'verbose_name_plural': 'Historie (kniha provozu)',
                'ordering': ['-date_run'],
            },
        ),
    ]
