# Generated by Django 2.2.28 on 2026-06-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaznamKnihaProvozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.DateField(verbose_name='Den')),
                ('cas', models.TimeField(verbose_name='Čas')),
                ('kde_server', models.CharField(max_length=100, verbose_name='Kde (server)')),
                ('dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dir')),
                ('popis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Popis (bližší specifikace/doména/sql)')),
                ('text', models.TextField(verbose_name='Text')),
                ('kdo', models.CharField(max_length=100, verbose_name='Kdo')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření záznamu')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'záznam kniha provozu',
                'verbose_name_plural': 'záznamy kniha provozu',
                'ordering': ['-den', '-cas'],
            },
        ),
        migrations.CreateModel(
            name='HistorieKnihaProvozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateTimeField(auto_now_add=True, verbose_name='Datum změny')),
                ('field_name', models.CharField(max_length=100, verbose_name='Pole')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Původní hodnota')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nová hodnota')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zaznam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id', to='kniha_provozu.ZaznamKnihaProvozu')),
            ],
            options={
                'verbose_name': 'Historie (kniha provozu)',
                'verbose_name_plural': 'Historie (kniha provozu)',
                'ordering': ['-date_run'],
            },
        ),
    ]
