# Generated by Django 2.2.28 on 2026-06-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniha_provozu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaznamknihaprovozu',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Text'),
        ),
    ]
