# Generated by Django 2.2.28 on 2026-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniha_provozu', '0003_redesign_script_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaznamknihaprovozu',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Spuštěno'),
        ),
    ]
