# Generated by Django 2.2 on 2022-12-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=35, verbose_name='Příjmení')),
            ],
            options={
                'verbose_name': 'autor/zadavatel',
                'verbose_name_plural': 'autoři/zadavatelé',
                'ordering': ['surname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=40, verbose_name='Příjmení')),
            ],
            options={
                'verbose_name': 'vlastník/řešitel',
                'verbose_name_plural': 'vlastníci/řešitelé)',
                'ordering': ['surname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='requirement_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type_text', models.CharField(max_length=30, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'typ pozadavku',
                'verbose_name_plural': 'typy pozadavku',
                'ordering': ['requirement_type_text'],
            },
        ),
        migrations.CreateModel(
            name='Work_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=20, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'stav prace',
                'verbose_name_plural': 'stavy praci',
                'ordering': ['status_text'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100, verbose_name='Požadavek')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Datum zadání')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Termín')),
                ('done', models.DateField(blank=True, null=True, verbose_name='Ukončeno')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Author', verbose_name='Autor')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Owner', verbose_name='Vlastník')),
                ('requirement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.requirement_type', verbose_name='Typ požadavku')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Work_status', verbose_name='Stav požadavku')),
            ],
        ),
    ]
