# Generated by Django 2.2 on 2022-12-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
