# Generated by Django 2.2 on 2022-12-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0003_auto_20221202_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='added',
            field=models.DateTimeField(verbose_name='Datum publikace'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
