# Generated by Django 2.2.28 on 2023-11-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0007_auto_20231107_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=25, verbose_name='Oznaceni')),
                ('name', models.CharField(max_length=35, verbose_name='Nazev')),
            ],
            options={
                'verbose_name': 'vlastník/řešitel',
                'verbose_name_plural': 'vlastníci/řešitelé)',
                'ordering': ['designation', 'name'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='cislo_jednaci',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Cislo jednaci'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='group_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Group', verbose_name='Oddeleni'),
        ),
    ]
