# Generated by Django 2.2.28 on 2023-11-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0008_auto_20231108_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Group_owner',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
