# Generated by Django 2.2.28 on 2023-11-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0009_auto_20231108_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_owner',
            options={'ordering': ['designation', 'name'], 'verbose_name': 'oddělení', 'verbose_name_plural': 'oddělení'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['surname', 'firstname'], 'verbose_name': 'řešitel', 'verbose_name_plural': 'řešitelé'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
