# Generated by Django 2.2.28 on 2023-11-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0010_auto_20231108_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='cislo_jednaci',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='čj'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
