# Generated by Django 2.2.28 on 2023-11-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0011_auto_20231108_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
