# Generated by Django 2.2 on 2023-11-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0013_auto_20231109_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Neuvedeno'), (1, 'Trvalý'), (2, 'Ginis - (e-mail)'), (3, 'Z porady')], default=0, verbose_name='Kategorie úkolu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement',
            field=models.CharField(max_length=100, verbose_name='Úkol'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
