# Generated by Django 2.2 on 2023-11-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0015_auto_20231120_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='group_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
