# Generated by Django 2.2 on 2023-11-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0020_auto_20231120_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['surname', 'firstname'], 'verbose_name': 'vlastnik/řešitel', 'verbose_name_plural': 'vlastnici/řešitelé'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
