# Generated by Django 2.2.28 on 2024-09-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0032_auto_20231213_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Neuvedeno'), (1, 'Trvalý'), (2, 'Ginis - (e-mail)'), (3, 'Z porady'), (4, 'Vlastní')], verbose_name='Kategorie úkolu'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
