# Generated by Django 2.2.28 on 2024-09-03 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0033_auto_20240902_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Zadal'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Owner', verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Work_status', verbose_name='Stav požadavku'),
        ),
    ]
