# Generated by Django 2.2.28 on 2025-10-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0034_auto_20240903_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement_type',
            options={'ordering': ['requirement_type_text'], 'verbose_name': 'typ požadavku', 'verbose_name_plural': 'typy požadavků'},
        ),
        migrations.AlterModelOptions(
            name='work_status',
            options={'ordering': ['status_text'], 'verbose_name': 'stav práce', 'verbose_name_plural': 'stavy prací'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='requirements_created', to=settings.AUTH_USER_MODEL, verbose_name='Zadal'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Neuvedeno'), (1, 'Trvalý'), (2, 'Ginis - (e-mail)'), (3, 'Z porady'), (4, 'Vlastní'), (5, 'Pracovní skupina C227'), (6, 'Hlavní projektový tým C227'), (7, 'Řídící výbor C227')], verbose_name='Kategorie úkolu'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cislo_jednaci',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Č. j.'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='group_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Oddělení'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='owner',
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT, related_name='requirements_owned', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník',limit_choices_to={'is_active': True},),
            ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
