# Generated by Django 2.2.28 on 2025-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0036_auto_20251023_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
        migrations.AlterField(
            model_name='requirement_type',
            name='requirement_type_text',
            field=models.CharField(max_length=30, unique=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='work_status',
            name='status_text',
            field=models.CharField(max_length=20, unique=True, verbose_name='Text'),
        ),
    ]
