# Generated by Django 2.2.28 on 2025-11-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0039_auto_20251105_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
