# Generated by Django 2.2.28 on 2026-06-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pozadavky', '0042_auto_20260629_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pozadavky.Requirement_type', verbose_name='Typ požadavku'),
        ),
    ]
