upstream dp2_site_uwsgi {
    server 127.0.0.1:8085;
}

server {
    listen 80;
    server_name db-firebird25-ctx.mv.cz;

    charset utf-8;

    location /static {
        alias /www/dp2_site/static_all;
    }

    location / {
        uwsgi_pass dp2_site_uwsgi;
        include /etc/nginx/uwsgi_params;
    }
}
